"""deleted bugs table

Revision ID: 1d984c946410
Revises: 8bcdd2947af7
Create Date: 2020-02-21 17:28:39.202937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d984c946410'
down_revision = '8bcdd2947af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bug_title', sa.TEXT(), nullable=True),
    sa.Column('bug_type', sa.TEXT(), nullable=True),
    sa.Column('bug_desc', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
