"""empty message

Revision ID: 7d57669e2104
Revises: 
Create Date: 2021-01-18 21:35:36.621436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d57669e2104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=7), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('claimDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('emailAddress', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('licenseID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licenseID'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_emailAddress'), 'users', ['emailAddress'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_creationDate'), 'sessions', ['creationDate'], unique=False)
    op.create_index(op.f('ix_sessions_name'), 'sessions', ['name'], unique=False)
    op.create_table('coordsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionID', sa.Integer(), nullable=True),
    sa.Column('obj1_x_pos', sa.Integer(), nullable=True),
    sa.Column('obj1_y_pos', sa.Integer(), nullable=True),
    sa.Column('obj1_width', sa.Integer(), nullable=True),
    sa.Column('obj1_height', sa.Integer(), nullable=True),
    sa.Column('obj1_color', sa.Integer(), nullable=True),
    sa.Column('obj2_x_pos', sa.Integer(), nullable=True),
    sa.Column('obj2_y_pos', sa.Integer(), nullable=True),
    sa.Column('obj2_width', sa.Integer(), nullable=True),
    sa.Column('obj2_height', sa.Integer(), nullable=True),
    sa.Column('obj2_color', sa.Integer(), nullable=True),
    sa.Column('obj1_color_B', sa.Integer(), nullable=True),
    sa.Column('obj2_color_B', sa.Integer(), nullable=True),
    sa.Column('obj1_color_C', sa.Integer(), nullable=True),
    sa.Column('obj2_color_C', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sessionID'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordsets')
    op.drop_index(op.f('ix_sessions_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_creationDate'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_emailAddress'), table_name='users')
    op.drop_table('users')
    op.drop_table('licenses')
    # ### end Alembic commands ###
