"""new tables

Revision ID: a080a94cd02b
Revises: 1d984c946410
Create Date: 2020-02-23 19:35:46.603667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a080a94cd02b'
down_revision = '1d984c946410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_properties',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('IID', sa.Integer(), nullable=True),
    sa.Column('SID', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('label_x', sa.Integer(), nullable=True),
    sa.Column('label_y', sa.Integer(), nullable=True),
    sa.Column('label_width', sa.Integer(), nullable=True),
    sa.Column('label_height', sa.Integer(), nullable=True),
    sa.Column('trial_type', sa.Integer(), nullable=True),
    sa.Column('trial_location', sa.Integer(), nullable=True),
    sa.Column('manipulations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('session_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('session_num', sa.Integer(), nullable=True),
    sa.Column('margin_size', sa.Integer(), nullable=True),
    sa.Column('diff_resolution', sa.Integer(), nullable=True),
    sa.Column('min_obj_distance', sa.Integer(), nullable=True),
    sa.Column('divisions_v', sa.Integer(), nullable=True),
    sa.Column('divisions_h', sa.Integer(), nullable=True),
    sa.Column('obj_width', sa.Integer(), nullable=True),
    sa.Column('obj_height', sa.Integer(), nullable=True),
    sa.Column('label_width_x', sa.Integer(), nullable=True),
    sa.Column('label_width_y', sa.Integer(), nullable=True),
    sa.Column('manip_option_1', sa.Integer(), nullable=True),
    sa.Column('manip_option_2', sa.Integer(), nullable=True),
    sa.Column('manip_option_3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_info')
    op.drop_table('generated_properties')
    # ### end Alembic commands ###
