"""Create tables

Revision ID: a22ea3a67a06
Revises: 
Create Date: 2020-02-21 15:35:53.933967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22ea3a67a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_title', sa.Text(), nullable=True),
    sa.Column('bug_type', sa.Text(), nullable=True),
    sa.Column('bug_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugs')
    # ### end Alembic commands ###
